language: node_js
dist: bionic

git:
  depth: 3
  submodules: false
  autocrlf: input

branches:
  only:
    - dev

node_js:
  - 12
env:
  - DIR=./src/webapp

install:
  - cd $DIR
  - npm install
script:
  - cd $DIR
  - npm test
