version: "3.4"

services:

  db:
    image: postgres:12
    restart: always
    volumes:
      - /var/docker/uroflow:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: feathers_api
      POSTGRES_HOST_AUTH_METHOD: trust

  api:
    image: node:12
    restart: always
    working_dir: /usr/src/myapp
    volumes:
      - ./api:/usr/src/myapp
    network_mode: host
    command: "npm run start"