version: "3.4"

services:

  postgres:
    image: postgres:12
    restart: always
    volumes:
      - /tmp/uroflow:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=uroflow
      - POSTGRES_DB=uroflow
      - POSTGRES_HOST_AUTH_METHOD=trust

  api:
    image: node:12
    restart: always
    volumes:
      - ./api:/usr/src/myapp
    working_dir: /usr/src/myapp
    ports:
      - 3010:3010
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=uroflow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=uroflow
    command: npm run start
    depends_on:
      - postgres
