version: "3.4"

services:

  postgres:
    image: postgres:12
    restart: always
    volumes:
      - /tmp/uroflow:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=uroflow
      - POSTGRES_DB=uroflow
      - POSTGRES_HOST_AUTH_METHOD=trust

  model:
    image: python:3.7
    restart: always
    volumes:
      - ./pytorch_model:/usr/src/myapp
      - audios:/usr/src/myapp/audios
      - curves:/usr/src/myapp/curves
    working_dir: /usr/src/myapp
    ports:
      - 3012:3012
    environment:
      - PORT=3012
      - MODEL_FILE=uroflow_fwdpass_20200311.py
    command: /bin/bash -c "apt update; apt install -y ffmpeg; python3 -m pip install -r requirements.txt; python3 app.py"

  api:
    image: node:12
    restart: always
    volumes:
      - ./api:/usr/src/myapp
      - audios:/usr/src/myapp/audios
      - curves:/usr/src/myapp/curves
    working_dir: /usr/src/myapp
    ports:
      - 3010:3010
    environment:
      - TEST=true
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=uroflow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=uroflow
    command: /bin/bash -c "npm i; npm run start"
    depends_on:
      - postgres
      - model

  web:
    image: node:12
    restart: always
    volumes:
      - ./webapp:/usr/src/myapp
    working_dir: /usr/src/myapp
    ports:
      - 3011:3000
    environment:
      - API_URL=http://api:3010
    command: /bin/bash -c "npm i; npm run start"
    depends_on:
      - postgres
      - api

volumes:

  postgres_db:

  audios:

  curves:
